export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const ADD_PRODUCT_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
export const GET_BEST_SELLER_SUCCESS = "GET_BEST_SELLER_SUCCESS";
export const GET_DAILY_DEALS_SUCCESS = "GET_DAILY_DEALS_SUCCESS";
export const GET_SIMILIAR_SUCCESS = "GET_SIMILIAR_SUCCESS";

export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES.SUCCESS";

export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const GET_FAVORITES_SUCCESS = "GET_FAVORITES_SUCCESS";
export const ADD_TO_FAV_SUCCESS = "ADD_TO_FAV_SUCCESS";
export const REMOVE_FROM_FAV_SUCCESS = "REMOVE_FROM_FAV_SUCCESS";
export const GET_PAST_ORDERS_SUCCESS = "GET_PAST_ORDERS_SUCCESS";
