export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const ADD_PRODUCT_SUCCESS = "GET_PRODUCTS_SUCCESS";

export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES.SUCCESS";
