export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const ADD_PRODUCT_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
export const GET_BEST_SELLER_SUCCESS = "GET_BEST_SELLER_SUCCESS";
export const GET_DAILY_DEALS_SUCCESS = "GET_DAILY_DEALS_SUCCESS";
export const GET_SIMILIAR_SUCCESS = "GET_SIMILIAR_SUCCESS";
export const GET_SPECIFICATIONS_SUCCESS = "GET_SPECIFICATIONS_SUCCESS";
export const REMOVE_SPECIFICATION_SUCCESS = "REMOVE_SPECIFICATION_SUCCESS";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";

export const SET_PRODUCT_VALIDATION_ERROR = "SET_PRODUCT_VALIDATION_ERROR";
export const CLEAR_PRODUCT_ERROR = "CLEAR_PRODUCT_ERROR";

export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES.SUCCESS";

export const CREATE_CART_SUCCESS = "CREATE_CART_SUCCESS";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_EXISTING_SUCCESS = "ADD_TO_CART_EXISTING_SUCCESS";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const COLLECT_CART_ITEM_PRICE = "COLLECT_CART_ITEM_PRICE";
export const CLEAR_CART = "CLEAR_CART";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const SET_AUTH_ERROR = "SET_AUTH_ERROR";
export const SET_USER_VALIDATION_ERROR = "SET_USER_VALIDATION_ERROR";

export const GET_FAVORITES_SUCCESS = "GET_FAVORITES_SUCCESS";
export const ADD_TO_FAV_SUCCESS = "ADD_TO_FAV_SUCCESS";
export const REMOVE_FROM_FAV_SUCCESS = "REMOVE_FROM_FAV_SUCCESS";
export const GET_PAST_ORDERS_SUCCESS = "GET_PAST_ORDERS_SUCCESS";

export const GET_EMAILS_SUCCESS = "GET_EMAILS_SUCCESS";
export const GET_FEEDBACKS_SUCCESS = "GET_FEEDBACKS_SUCCESS";

export const SET_ORDER_ERROR = "SET_ORDER_ERROR";
export const SET_PAYMENT_ERROR = "SET_PAYMENT_ERROR";
export const COMPLETE_ORDER_SUCCESS = "COMPLETE_ORDER_SUCCESS";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const CONFIRM_ORDER_SUCCESS = "CONFIRM_ORDER_SUCCESS";

export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const SET_SUCCESS = "SET_SUCCESS";
export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
